services:
  mecanetbackend:
    image: mecanetbackend:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - LCPASSWORD=${LCPASSWORD}